"""Module-specific data models — extends ContentAsset without modifying the original."""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any


@dataclass
class GrowthPage:
    """A page generated by the Pipeleap SaaS Growth Engine."""
    slug: str
    page_type: str
    title: str
    seo_title: str
    meta_description: str
    h1: str
    body_markdown: str
    schema_markup: list[dict[str, Any]]
    call_to_action: str
    primary_keyword: str
    target_keywords: list[str]
    internal_links: list[dict[str, str]]
    uniqueness_score: float = 1.0
    # SEO meta tags
    canonical_url: str = ""
    og_meta: dict[str, str] = field(default_factory=dict)
    twitter_meta: dict[str, str] = field(default_factory=dict)
    publish_date: str = ""
    modified_date: str = ""
    author_name: str = ""
    author_slug: str = ""
    breadcrumbs: list[tuple[str, str]] = field(default_factory=list)
    # Module metadata
    module: str = "pipeleap-seo-engine"
    industry: str = "SaaS"
    role: str = ""
    use_case: str = ""
    competitor: str = ""
    glossary_term: str = ""
    integration_partner: str = ""
    pain_points: list[str] = field(default_factory=list)
    intent: str = ""
    word_count: int = 0
    topical_pillar: str = ""

    def __post_init__(self) -> None:
        if not self.publish_date:
            self.publish_date = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        if not self.modified_date:
            self.modified_date = self.publish_date
        if not self.word_count:
            self.word_count = len(self.body_markdown.split())

    def to_dict(self) -> dict[str, Any]:
        return {
            "slug": self.slug,
            "page_type": self.page_type,
            "title": self.title,
            "seo_title": self.seo_title,
            "meta_description": self.meta_description,
            "canonical_url": self.canonical_url,
            "og_meta": self.og_meta,
            "twitter_meta": self.twitter_meta,
            "h1": self.h1,
            "body_markdown": self.body_markdown,
            "schema_markup": self.schema_markup,
            "call_to_action": self.call_to_action,
            "primary_keyword": self.primary_keyword,
            "target_keywords": self.target_keywords,
            "internal_links": self.internal_links,
            "uniqueness_score": self.uniqueness_score,
            "publish_date": self.publish_date,
            "modified_date": self.modified_date,
            "author_name": self.author_name,
            "author_slug": self.author_slug,
            "breadcrumbs": self.breadcrumbs,
            "module": self.module,
            "industry": self.industry,
            "role": self.role,
            "use_case": self.use_case,
            "competitor": self.competitor,
            "glossary_term": self.glossary_term,
            "integration_partner": self.integration_partner,
            "pain_points": self.pain_points,
            "intent": self.intent,
            "word_count": self.word_count,
            "topical_pillar": self.topical_pillar,
        }

    def to_content_asset(self) -> Any:
        """Convert to the main agent's ContentAsset for CMS publishing."""
        from utils.models import ContentAsset
        return ContentAsset(
            slug=self.slug,
            page_type=self.page_type,
            title=self.title,
            seo_title=self.seo_title,
            meta_description=self.meta_description,
            h1=self.h1,
            body_markdown=self.body_markdown,
            schema_markup=self.schema_markup,
            internal_link_suggestions=[],
            call_to_action=self.call_to_action,
            source_keywords=self.target_keywords,
            target_persona=self._persona(),
            eeat_notes=self._eeat_notes(),
        )

    def _persona(self) -> str:
        role_map = {
            "cro": "Chief Revenue Officers and revenue leadership",
            "cso": "Chief Sales Officers and sales organization leaders",
            "vp_sales": "VP of Sales and sales team leaders",
            "sales_manager": "Sales managers and team leads",
            "founder": "SaaS founders and early-stage GTM leads",
        }
        return role_map.get(self.role, "SaaS revenue and GTM teams")

    def _eeat_notes(self) -> list[str]:
        notes = [
            f"Author: {self.author_name} — add byline, credentials, and headshot before publishing." if self.author_name else "Add a named author byline with credentials before publishing.",
            "Add product screenshots or workflow diagrams to demonstrate first-hand experience.",
            "Include at least one specific, verifiable outcome metric (reply rate, pipeline lift, time saved).",
        ]
        return notes


@dataclass
class GrowthEngineReport:
    """Full output report from one growth engine run."""
    generated_at: str
    pages_generated: list[GrowthPage]
    keyword_matrix: list[dict[str, Any]]
    internal_link_map: dict[str, list[dict[str, str]]]
    topical_coverage: dict[str, Any]
    integration_notes: list[str]
    output_directory: str

    def to_dict(self) -> dict[str, Any]:
        breakdown = self._type_breakdown()
        avg_wc = round(sum(p.word_count for p in self.pages_generated) / max(len(self.pages_generated), 1))
        return {
            "generated_at": self.generated_at,
            "module": "pipeleap-seo-engine",
            "pages_generated": [p.to_dict() for p in self.pages_generated],
            "total_pages": len(self.pages_generated),
            "page_type_breakdown": breakdown,
            "avg_word_count": avg_wc,
            "keyword_matrix_size": len(self.keyword_matrix),
            "topical_coverage": self.topical_coverage,
            "integration_notes": self.integration_notes,
            "output_directory": self.output_directory,
        }

    def _type_breakdown(self) -> dict[str, int]:
        from collections import Counter
        return dict(Counter(p.page_type for p in self.pages_generated))
