"""
Funnel stage definitions for Pipeleap's revenue path architecture.

TOFU (awareness) → MOFU (consideration) → BOFU (decision) → SQL (sales qualified) → Demo

Every page type generated by the growth engine is assigned a stage.
Each stage has:
  - soft CTA copy (no hard-sell free-trial pushes)
  - conversion goal
  - next-step page type (for internal link nurturing)
  - schema intent hint (for og:type, article type)
"""
from __future__ import annotations

# ── Stage definitions ──────────────────────────────────────────────────────────
FUNNEL_STAGES: dict[str, dict] = {
    "TOFU": {
        "label": "Top of Funnel — Awareness",
        "intent": "informational",
        "goal": "educate and capture attention",
        "cta_primary": "Download the outbound workflow framework — free, no signup",
        "cta_secondary": "See how SaaS teams build predictable pipeline",
        "cta_url_primary": "https://pipeleap.com/blog",
        "cta_url_secondary": "https://pipeleap.com/how-it-works",
        "cta_urgency": "",
        "next_stage": "MOFU",
    },
    "MOFU": {
        "label": "Middle of Funnel — Consideration",
        "intent": "commercial",
        "goal": "show Pipeleap solves the specific problem",
        "cta_primary": "See how Pipeleap works for your team",
        "cta_secondary": "Compare Pipeleap to your current stack",
        "cta_url_primary": "https://pipeleap.com/how-it-works",
        "cta_url_secondary": "https://pipeleap.com/blog",
        "cta_urgency": "Most teams implement a working workflow in under 2 weeks.",
        "next_stage": "BOFU",
    },
    "BOFU": {
        "label": "Bottom of Funnel — Decision",
        "intent": "transactional",
        "goal": "convert to demo or GTM audit",
        "cta_primary": "Get a free GTM audit — we map your exact workflow gaps",
        "cta_secondary": "Book a 30-minute pipeline strategy call",
        "cta_url_primary": "https://pipeleap.com/gtm-audit",
        "cta_url_secondary": "https://pipeleap.com/contact",
        "cta_urgency": "Audits are completed within 48 hours and include a full workflow blueprint.",
        "next_stage": "SQL",
    },
    "SQL": {
        "label": "Sales Qualified — Demo",
        "intent": "transactional",
        "goal": "book demo or start onboarding",
        "cta_primary": "Book your personalised Pipeleap demo",
        "cta_secondary": "Talk to a workflow automation specialist",
        "cta_url_primary": "https://pipeleap.com/gtm-audit",
        "cta_url_secondary": "https://pipeleap.com/contact",
        "cta_urgency": "Same-week demo slots available for qualified SaaS teams.",
        "next_stage": None,
    },
}

# ── Page type → funnel stage mapping ──────────────────────────────────────────
PAGE_TYPE_STAGE: dict[str, str] = {
    # TOFU — informational, awareness
    "blog_post":            "TOFU",
    "glossary_page":        "TOFU",
    "problem_page":         "TOFU",

    # MOFU — commercial, consideration
    "use_case_page":        "MOFU",
    "role_page":            "MOFU",
    "integration_page":     "MOFU",
    "workflow_page":        "MOFU",
    "workflow_recipe":      "MOFU",

    # BOFU — transactional, decision
    "bofu_page":            "BOFU",
    "objection_page":       "BOFU",
    "landing_page":         "BOFU",

    # SQL — ready to buy
    "demo_page":            "SQL",
    "roi_page":             "SQL",
}


def stage_for(page_type: str) -> str:
    return PAGE_TYPE_STAGE.get(page_type, "MOFU")


def cta_for(page_type: str) -> dict:
    """Return the CTA dict for a given page type."""
    stage = stage_for(page_type)
    return FUNNEL_STAGES[stage]


def next_stage_cta(page_type: str) -> dict | None:
    """Return the CTA for the NEXT funnel stage after this page type."""
    stage = stage_for(page_type)
    next_stage = FUNNEL_STAGES[stage].get("next_stage")
    if next_stage:
        return FUNNEL_STAGES[next_stage]
    return None


# ── Role-based conversion journeys ────────────────────────────────────────────
# Maps each persona to their specific pain, desired outcome, and BOFU CTA angle.
ROLE_JOURNEYS: dict[str, dict] = {
    "founder": {
        "tofu_hook": "Why founder-led outbound burns out before product-market fit",
        "mofu_hook": "How SaaS founders build pipeline without hiring SDRs",
        "bofu_hook": "Founder GTM audit — map your outbound workflow in 48 hours",
        "bofu_cta": "Get your founder GTM audit",
        "demo_angle": "Show me how to run outbound without a sales hire",
        "objections": ["too complex for early stage", "we don't have a sales process yet", "cost vs headcount ROI"],
    },
    "vp_sales": {
        "tofu_hook": "Why VP Sales inherit broken outbound stacks",
        "mofu_hook": "How VP Sales build repeatable pipeline systems at 1-10M ARR",
        "bofu_hook": "Pipeline system audit — identify your outbound execution gaps",
        "bofu_cta": "Audit my outbound pipeline system",
        "demo_angle": "Show me how to standardize outbound across my team",
        "objections": ["team adoption resistance", "integration with existing CRM", "vs hiring another SDR"],
    },
    "revops": {
        "tofu_hook": "Why RevOps teams spend 80% of time maintaining integrations",
        "mofu_hook": "How RevOps teams replace fragmented tools with one workflow engine",
        "bofu_hook": "RevOps workflow audit — identify your tool consolidation opportunity",
        "bofu_cta": "Audit my RevOps workflow stack",
        "demo_angle": "Show me how to govern outbound workflows across our tools",
        "objections": ["n8n vs Zapier vs Make decision", "integration complexity", "change management"],
    },
    "cro": {
        "tofu_hook": "Why CROs miss pipeline targets despite headcount growth",
        "mofu_hook": "How CROs build predictable pipeline through workflow governance",
        "bofu_hook": "Revenue workflow audit — map where your pipeline breaks down",
        "bofu_cta": "Get a revenue workflow audit",
        "demo_angle": "Show me how to make outbound predictable at our scale",
        "objections": ["ROI vs enterprise sales tooling", "board-level justification", "timeline to impact"],
    },
    "sales_manager": {
        "tofu_hook": "Why sales managers can't scale output without adding reps",
        "mofu_hook": "How sales managers automate outbound without micromanaging execution",
        "bofu_hook": "Sales workflow audit — identify your team's automation gaps",
        "bofu_cta": "Audit my team's outbound workflow",
        "demo_angle": "Show me how to automate outbound without losing visibility",
        "objections": ["rep buy-in", "quota attribution", "training time"],
    },
}


# ── PAA (People Also Ask) question banks by topic ─────────────────────────────
PAA_BANKS: dict[str, list[str]] = {
    "outbound_automation": [
        "What is outbound sales automation?",
        "How do you automate B2B outbound emails?",
        "What is the best outbound automation platform for SaaS?",
        "How do you build a repeatable outbound sales system?",
        "What is signal-based outbound?",
        "How do you scale cold outreach without adding SDRs?",
        "What tools do RevOps teams use for outbound automation?",
        "How do you measure outbound workflow performance?",
    ],
    "pipeline_generation": [
        "What is predictable pipeline generation?",
        "How do SaaS companies build a predictable sales pipeline?",
        "What is a pipeline generation system?",
        "How do you generate pipeline without a large sales team?",
        "What causes unpredictable pipeline in SaaS?",
        "How do you automate pipeline generation?",
    ],
    "workflow_orchestration": [
        "What is workflow orchestration in sales?",
        "How does workflow orchestration differ from automation?",
        "What is an n8n workflow for outbound sales?",
        "How do you orchestrate multi-channel outbound workflows?",
        "What is the difference between a sequencer and a workflow orchestration tool?",
    ],
    "revops": [
        "What does a RevOps team do?",
        "How do RevOps teams automate workflows?",
        "What is revenue operations automation?",
        "How do you build a RevOps tech stack?",
        "What tools do RevOps teams use?",
    ],
}


def paa_questions_for(topic: str, limit: int = 4) -> list[str]:
    bank = PAA_BANKS.get(topic, PAA_BANKS["outbound_automation"])
    return bank[:limit]
