"""
Internal linking engine for the Pipeleap SaaS Growth Engine.
Links ONLY between pages generated by this module.
Does NOT touch or read existing agent link structures.

Revenue path rules (added alongside existing rules):
  - BOFU/objection pages → top MOFU use-case and role pages (show value before conversion ask)
  - Glossary pages → most relevant MOFU use-case page (educate → consider)
  - Integration pages → comparison pages (consideration → decision)
  - All BOFU pages → GTM audit page (direct conversion link)
"""
from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from modules.pipeleap_seo_engine.models import GrowthPage

AUDIT_URL = "https://pipeleap.com/gtm-audit"


class GrowthLinkingEngine:
    """
    Builds an internal link map for all growth engine pages.
    Structural rules (original):
    - Role pages ↔ Use case pages (bidirectional)
    - Competitor pages → Role pages
    - Problem pages → Use case pages + Role pages
    - All pages → workflow orchestration pillar page

    Revenue path rules (extended):
    - BOFU/objection pages → top MOFU use-case + role pages
    - Glossary pages → most relevant use-case page
    - Integration pages → comparison pages for the same tool
    - All BOFU/SQL pages → GTM audit CTA link
    """

    PILLAR_SLUG = "saas-workflow-orchestration"
    PILLAR_ANCHOR = "SaaS workflow orchestration"
    BOFU_TYPES = {"bofu_page", "objection_page", "landing_page"}

    def build(self, pages: list["GrowthPage"]) -> dict[str, list[dict[str, str]]]:
        link_map: dict[str, list[dict[str, str]]] = {p.slug: [] for p in pages}

        role_pages       = [p for p in pages if p.page_type == "role_page"]
        use_case_pages   = [p for p in pages if p.page_type == "use_case_page"]
        problem_pages    = [p for p in pages if p.page_type == "problem_page"]
        glossary_pages   = [p for p in pages if p.page_type == "glossary_page"]
        integration_pages= [p for p in pages if p.page_type == "integration_page"]
        bofu_pages       = [p for p in pages if p.page_type in self.BOFU_TYPES]
        pillar           = next((p for p in use_case_pages if p.slug == self.PILLAR_SLUG), None)

        # ── Original structural rules ──────────────────────────────────────────

        # Role ↔ Use case (bidirectional)
        for role_page in role_pages:
            for uc_page in use_case_pages[:3]:
                if uc_page.slug != role_page.slug:
                    link_map[role_page.slug].append({
                        "anchor": uc_page.title.split("|")[0].strip(),
                        "url": f"/blog/{uc_page.slug}",
                    })
                    link_map[uc_page.slug].append({
                        "anchor": role_page.title.split("|")[0].strip(),
                        "url": f"/blog/{role_page.slug}",
                    })

        # Problem pages → Use cases + top role pages
        for prob_page in problem_pages:
            for uc_page in use_case_pages[:2]:
                link_map[prob_page.slug].append({
                    "anchor": uc_page.title.split("|")[0].strip(),
                    "url": f"/blog/{uc_page.slug}",
                })
            for role_page in role_pages[:2]:
                link_map[prob_page.slug].append({
                    "anchor": role_page.title.split("|")[0].strip(),
                    "url": f"/blog/{role_page.slug}",
                })

        # All pages → pillar
        if pillar:
            for page in pages:
                if page.slug != self.PILLAR_SLUG:
                    already = any(l["url"].endswith(self.PILLAR_SLUG) for l in link_map[page.slug])
                    if not already:
                        link_map[page.slug].append({
                            "anchor": self.PILLAR_ANCHOR,
                            "url": f"/blog/{self.PILLAR_SLUG}",
                        })

        # ── Revenue path rules (extended) ─────────────────────────────────────

        # BOFU/objection pages → top MOFU pages (show value before asking for conversion)
        for bofu_page in bofu_pages:
            for uc_page in use_case_pages[:1]:
                link_map[bofu_page.slug].append({
                    "anchor": f"how Pipeleap handles {uc_page.use_case or 'outbound automation'}",
                    "url": f"/blog/{uc_page.slug}",
                })
            for role_page in role_pages[:1]:
                link_map[bofu_page.slug].append({
                    "anchor": f"Pipeleap for {role_page.role or 'your team'}",
                    "url": f"/blog/{role_page.slug}",
                })

        # Glossary pages → most relevant use-case page (educate → consider)
        for gloss_page in glossary_pages:
            for uc_page in use_case_pages[:1]:
                link_map[gloss_page.slug].append({
                    "anchor": f"see how Pipeleap applies this to {uc_page.use_case or 'outbound'}",
                    "url": f"/blog/{uc_page.slug}",
                })

        # Integration pages → use case page for same tool context
        for int_page in integration_pages:
            partner = (int_page.integration_partner or "").lower()
            matching_uc = next(
                (p for p in use_case_pages if partner and partner in (p.use_case or "").lower()),
                None
            )
            if matching_uc:
                link_map[int_page.slug].append({
                    "anchor": f"Pipeleap for {int_page.integration_partner}",
                    "url": f"/blog/{matching_comp.slug}",
                })

        # All BOFU/SQL pages get a direct GTM audit link
        for bofu_page in bofu_pages:
            audit_entry = {
                "anchor": "get a free GTM audit",
                "url": f"{AUDIT_URL}?utm_source=organic&utm_medium=seo&utm_campaign=linking_engine&utm_content={bofu_page.slug}",
            }
            already = any("gtm-audit" in l["url"] for l in link_map[bofu_page.slug])
            if not already:
                link_map[bofu_page.slug].append(audit_entry)

        # ── Deduplicate and cap ────────────────────────────────────────────────
        for slug in link_map:
            seen_urls: set[str] = set()
            deduped = []
            for link in link_map[slug]:
                if link["url"] not in seen_urls:
                    seen_urls.add(link["url"])
                    deduped.append(link)
            link_map[slug] = deduped[:1]  # Strict cap: Only one primary internal link per blog

        return link_map
